# Generated by Django 5.1 on 2025-10-27 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id_estadio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('fecha_inaguracion', models.DateField()),
                ('direccion', models.TextField()),
                ('cesped_natural', models.CharField(choices=[('natural', 'Natural'), ('artificial', 'Artificial'), ('mixto', 'Mixto')], default='natural', max_length=10)),
                ('imagen_estadio', models.ImageField(blank=True, null=True, upload_to='img_estadios/')),
            ],
            options={
                'verbose_name': 'Estadio',
                'verbose_name_plural': 'Estadios',
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id_partido', models.AutoField(primary_key=True, serialize=False)),
                ('equipo_local', models.CharField(max_length=100)),
                ('equipo_visitante', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('goles_locales', models.IntegerField(default=0)),
                ('goles_visitantes', models.IntegerField(default=0)),
                ('estadio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='app_futbol.estadio')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['-fecha'],
            },
        ),
    ]
